#!/usr/bin/env zsh

CLOJURE="/usr/local/Cellar/clojure-contrib/1.2.0/clojure-contrib.jar"
JAVA_CMD="/usr/libexec/java_home"

if [ -f $CLOJURE ]; then
    export CLASSPATH=$CLASSPATH:$CLOJURE
fi

if [ -f $JAVA_CMD ]; then
    export JAVA_HOME=$($JAVA_CMD)
fi
